### ISSUE TITLE
lite: pyodide 0.20.x support

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotkernel#113]
Robot tests / tasks with errors fail with pyodide 0.20.0.

Maybe just wait for the next pyodide release.

```
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/site-packages/robotkernel/display_pyolite.py", line 115, in run
    return self.do_execute(code, silent=False)
  File "/lib/python3.10/site-packages/robotkernel/kernel.py", line 269, in do_execute
    result = execute_robot(
  File "/lib/python3.10/site-packages/robotkernel/executors.py", line 222, in execute_robot
    reply = run_robot_suite(
  File "/lib/python3.10/site-packages/robotkernel/executors.py", line 268, in run_robot_suite
    results = suite.run(outputdir=path, stdout=stdout, listener=listeners)
  File "/lib/python3.10/site-packages/robot/running/model.py", line 402, in run
    with STOP_SIGNAL_MONITOR:
  File "/lib/python3.10/site-packages/robot/running/signalhandler.py", line 50, in __enter__
    self._register_signal_handler(signum)
  File "/lib/python3.10/site-packages/robot/running/signalhandler.py", line 64, in _register_signal_handler
    signal.signal(signum, self)
  File "/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
OSError: [Errno 0] Error
```

**Comment by bollwyvl** [comment]
Little update: we're getting close to a jupyterlite release with pyodide 0.21.2 and lab 3.4.7, and better support for #99. Hopefully this week... and, of note: the kernel filesystem and server/browser contents now _basically_ unified, which means it would be possible to `import` and `Library` relative paths that are deployed with the application, or written on the fly.

Probably worth taking another look when that release lands.
