### ISSUE TITLE
Integration with JupyterHub (TLJH) Kernel always died (auto-restarting)

### ISSUE THREAD

**Issue by HoudayerPierre** [robots-from-jupyter/robotkernel#49]
Hello, I have a JupyterHub (TLJH) with JupyterLab installed, all behind a reverse HTTP/WebSocket proxy (python kernel works).
The robotkernel was installed and I can see it in the luncher tab.
If I open a notebook with a robot kernel the kernel seems to not start. If press the start button nothing is running and no output is shown.
After some time the kernel status is marked as "autorestarting" and a popup is shown.

```
Kernel Restarting
The kernel for RobotFramework/Untitled.ipynb appears to have died. It will restart automatically.
```

For installation I use a jupyter terminal (my user is admin) just using `sudo` before : 
```
sudo jupyter labextension install jupyterlab_robotmode
sudo jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by datakurre** [comment]
@bollwyvl Any ideas what could cause this? Or how to get more traceback for this issue? Doesn’t Binder use somewhat similar setup, and it works fine?

**Comment by bollwyvl** [comment]
Does ipython work?

There should be more logs than what is in the browser... These are likely
on a systemd unit (e.g journalctl -u) and are for the specific single user
notebook server, not the hub unit.

**Comment by HoudayerPierre** [comment]
Yes ipython works in this setup.

from a jupyter terminal with : 
`sudo journalctl -u jupyterhub -f`
```
sept. 20 18:24:54 jupyterlab python3[1099]: [I 2020-09-20 18:24:54.400 JupyterHub proxy:319] Checking routes
sept. 20 18:24:55 jupyterlab python3[1099]: [I 2020-09-20 18:24:55.017 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 76.31ms
sept. 20 18:25:55 jupyterlab python3[1099]: [I 2020-09-20 18:25:55.011 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 70.32ms
sept. 20 18:26:12 jupyterlab python3[1099]: [I 2020-09-20 18:26:12.897 JupyterHub log:174] 200 POST /jupyterlab/hub/api/users/pitdu53/activity (pitdu53@127.0.0.1) 199.82ms
sept. 20 18:26:47 jupyterlab python3[1099]: [I 2020-09-20 18:26:47.207 JupyterHub log:174] 200 GET /jupyterlab/hub/api/authorizations/token/[secret] (pitdu53@127.0.0.1) 176.90ms
sept. 20 18:26:55 jupyterlab python3[1099]: [I 2020-09-20 18:26:55.018 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 76.99ms
sept. 20 18:27:55 jupyterlab python3[1099]: [I 2020-09-20 18:27:55.025 JupyterHub log:174] 200 GET /jupyterlab/hub/api/users (cull-idle@127.0.0.1) 83.65ms
```

`journalctl -u jupyter-pitdu53`

```
sept. 20 18:22:05 jupyterlab bash[3445]: [I 2020-09-20 18:22:05.762 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (1/5), new random ports
sept. 20 18:22:06 jupyterlab bash[3445]: Traceback (most recent call last):
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/opt/tljh/user/lib/python3.7/runpy.py", line 193, in _run_module_as_main
sept. 20 18:22:06 jupyterlab bash[3445]:     "__main__", mod_spec)
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/opt/tljh/user/lib/python3.7/runpy.py", line 85, in _run_code
sept. 20 18:22:06 jupyterlab bash[3445]:     exec(code, run_globals)
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/home/jupyter-pitdu53/.local/lib/python3.7/site-packages/robotkernel/kernel.py", line 11, in <module>
sept. 20 18:22:06 jupyterlab bash[3445]:     from robotkernel.executors import execute_python
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/home/jupyter-pitdu53/.local/lib/python3.7/site-packages/robotkernel/executors.py", line 17, in <module>
sept. 20 18:22:06 jupyterlab bash[3445]:     from robotkernel.utils import data_uri
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/home/jupyter-pitdu53/.local/lib/python3.7/site-packages/robotkernel/utils.py", line 7, in <module>
sept. 20 18:22:06 jupyterlab bash[3445]:     from lunr.builder import Builder
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/home/jupyter-pitdu53/.local/lib/python3.7/site-packages/lunr/__init__.py", line 5, in <module>
sept. 20 18:22:06 jupyterlab bash[3445]:     from lunr.__main__ import lunr
sept. 20 18:22:06 jupyterlab bash[3445]:   File "/home/jupyter-pitdu53/.local/lib/python3.7/site-packages/lunr/__main__.py", line 4, in <module>
sept. 20 18:22:06 jupyterlab bash[3445]:     from past.builtins import basestring
sept. 20 18:22:06 jupyterlab bash[3445]: ModuleNotFoundError: No module named 'past'
```

**Comment by datakurre** [comment]
I have never seen that before, but if it is really “lunr” Python package breaking things, its current master seem to have dropped Python 2 support and at least that error cannot happen anymore.

Maybe

    pip install git+https://github.com/yeraydiazdiaz/lunr.py@master

**Comment by HoudayerPierre** [comment]
From a jupyter terminal : 
```
(base) jupyter-pitdu53@jupyterlab:~$ pip install git+https://github.com/yeraydiazdiaz/lunr.py@master
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/yeraydiazdiaz/lunr.py@master
  Cloning https://github.com/yeraydiazdiaz/lunr.py (to revision master) to /tmp/pip-req-build-hnxboncv
  Running command git clone -q https://github.com/yeraydiazdiaz/lunr.py /tmp/pip-req-build-hnxboncv
Requirement already satisfied (use --upgrade to upgrade): lunr==0.5.8 from git+https://github.com/yeraydiazdiaz/lunr.py@master in ./.local/lib/python3.7/site-packages
Building wheels for collected packages: lunr
  Building wheel for lunr (setup.py) ... done
  Created wheel for lunr: filename=lunr-0.5.8-py2.py3-none-any.whl size=34695 sha256=b938d76b3ee266fe5dfe46b65c4fe6e835852ae7c686a19349a963242fb63a25
  Stored in directory: /tmp/pip-ephem-wheel-cache-jsph6cs_/wheels/88/01/7b/233afaae653e5e4c68d4893d37b9a4966f31cf16aaf51a0e6d
Successfully built lunr
```
Then reboot, but same output.

**Comment by HoudayerPierre** [comment]
For the module past, I search `python past module` here [https://pypi.org/project/past/](https://pypi.org/project/past/) 

from jupyter terminal : 
```
(base) jupyter-pitdu53@jupyterlab:~$ pip install future
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: future in /usr/bin/anaconda3/lib/python3.7/site-packages (0.18.2)
```

**Comment by bollwyvl** [comment]
Hm.... you have a lot of different python environments that are interacting
with each other (I see at least 3, plus potentially a user site
packages).... i guess if you can `conda list` and `pip freeze` on each of
the offending environments, that might help shed some light on it... if at
all possible, try and do everything with pip OR conda, the mix of the two
can be very unpredictable... and hot installing from master can make
_everything_ go haywire...

**Comment by HoudayerPierre** [comment]
With a jupyter terminal with `pip freeze` I can see : 
```
future==0.18.2
lunr==0.5.8
robotframework==3.2.2
robotkernel==1.4.0
```
Did you want specific items or the full output ?

With `conda list` there is no robot* item in the list.

**Comment by HoudayerPierre** [comment]
with a jupyter terminal : 
```
(base) jupyter-pitdu53@jupyterlab:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lunr
>>> import past
>>> from past.builtins import basestring
>>> exit()
```
I'm lost but this is two differents environnement from the robot kernel and my jupyter terminal ?

**Comment by datakurre** [comment]
@HoudayerPierre And `journalctl -u jupyter-pitdu53` still shows robotkernel crashing with a Python stacktrace?

And yes, I am still puzzled too, because I still have never seen that error before.

Have you already tried creating a new clean Conda Python 3 environment and installing just robotkernel with pip? I used to install robotkernel with miniconda and pip and it used to just work.

**Comment by HoudayerPierre** [comment]
Yes same stacktrace as before with the error in past module.
What did you recommand to do because in the terminal I tried : 
```
sudo jupyter labextension uninstall jupyterlab_robotmode
sudo jupyter labextension uninstall @jupyter-widgets/jupyterlab-manage
pip uninstall robotkernel
```
and followed the readme with (just added `sudo`) : 
```
pip install robotkernel
sudo jupyter labextension install jupyterlab_robotmode
sudo jupyter labextension install @jupyter-widgets/jupyterlab-manage
```

**Comment by datakurre** [comment]
But it should not be possible to get the same exception with `pip install git+https://github.com/yeraydiazdiaz/lunr.py@master --upgrade`, because master no longer imports `past`... :eyes:

That said, the most probably issue, as Nick noticed, comes from the Python setup in the JupyterHub node in question. In this issue we have seen that the environment has at least

1. a custom  Python installation at /opt/tljh/user/lib/python3.7 (maybe has /opt/tljh/user/lib/python3.7/site-packages/)
2. conda Python at /usr/bin/anaconda3/lib/python3.7/site-packages
3. userspace packages at /home/jupyter-pitdu53/.local/lib/python3.7/site-packages

With a clean setup, I believe, we should see only one of these paths in logs / stacktraces.

I would expect making a new clean Python virtualenv / Conda environment for robotkernel and pip installing robotkernel there to work, but I don't know how it should be configured for JupyterHub to launch robotkernel from that environment :thinking:

**Comment by HoudayerPierre** [comment]
Yes if i use `--upgrade` : `pip install git+https://github.com/yeraydiazdiaz/lunr.py@master --upgrade` :
The kernel is now on `idle`.
